// Writes src/meta.ts: the endpoint table without zod schemas, for clients that only need method,
// path and auth (keeps validation code out of every page). Run: pnpm --filter @logicpath/contracts gen
import { writeFileSync } from 'node:fs';
import { ENDPOINTS, type Endpoint } from '../src/routes';

const rows = Object.entries(ENDPOINTS as Record<string, Endpoint>).map(([id, e]) => {
  const meta: Record<string, unknown> = {
    method: e.method,
    path: e.path,
    service: e.service,
    auth: e.auth,
    status: e.status,
    summary: e.summary,
  };
  if (e.bodyType) meta.bodyType = e.bodyType;
  if (e.planned) meta.planned = e.planned;
  return `  ${JSON.stringify(id)}: ${JSON.stringify(meta)},`;
});

const source = `// GENERATED by scripts/gen-meta.ts from src/routes.ts. Do not edit by hand.
import type { Auth, Method } from './route-types';

export interface EndpointMeta {
  method: Method;
  path: string;
  service: string;
  auth: Auth;
  status: number;
  summary: string;
  bodyType?: 'json' | 'multipart';
  planned?: string;
}

export const ENDPOINT_META: Record<string, EndpointMeta> = {
${rows.join('\n')}
};

/** Fills \`:name\` segments: pathFor('/v1/classes/:id', { id }) → /v1/classes/123 */
export function pathFor(path: string, params?: Record<string, string | number>): string {
  return path.replace(/:([A-Za-z]+)/g, (_, name: string) => {
    const value = params?.[name];
    if (value === undefined) throw new Error(\`missing path parameter \${name} for \${path}\`);
    return encodeURIComponent(String(value));
  });
}
`;
writeFileSync(new URL('../src/meta.ts', import.meta.url), source);
console.log(`wrote src/meta.ts (${rows.length} endpoints)`);
