#!/usr/bin/env node
// Writes infra/vm/docker-compose.yml, Caddyfile and postgres-init.sh: the whole backend on one
// small server (Oracle Cloud Always Free ARM VM, or any Docker host). Images come from GHCR.
// Same service list as every other generator (infra/dev/services.mjs).
import { copyFileSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICES } from '../dev/services.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const NAMES = Object.keys(SERVICES).filter((name) =>
  existsSync(join(root, 'services', name, 'src', 'main.ts')),
);
const IMAGE = 'ghcr.io/abhayvaishnav09/dsa-learning';
const lines = [];
const w = (s = '') => lines.push(s);

w('# GENERATED by infra/vm/generate.mjs. Do not edit by hand.');
w('# Needs a .env next to it (cloud-init writes one): TAG, DOMAIN, WEB_ORIGIN, INTERNAL_TOKEN,');
w('# POSTGRES_PASSWORD, ADMIN_EMAIL, ADMIN_PASSWORD, and optionally SMTP_URL, MAIL_FROM.');
w('name: logicpath');
w();
w('x-service: &service');
w('  restart: unless-stopped');
w('  depends_on:');
w('    postgres: { condition: service_healthy }');
w('    nats: { condition: service_started }');
w('  environment: &service-env');
w('    NODE_ENV: production');
w('    HOST: 0.0.0.0');
w('    PORT: "8080"');
w('    NATS_URL: nats://nats:4222');
w('    JWKS_URL: http://identity:8080/.well-known/jwks.json');
for (const name of NAMES) w(`    ${name.toUpperCase()}_URL: http://${name}:8080`);
w('    SMTP_URL: ${SMTP_URL:-}');
w('    MAIL_FROM: ${MAIL_FROM:-LogicPath <no-reply@logicpath.dev>}');
w('    PUBLIC_WEB_URL: ${WEB_ORIGIN}');
w('    PUBLIC_API_URL: https://${DOMAIN}');
w('    INTERNAL_TOKEN: ${INTERNAL_TOKEN}');
w('    LOG_LEVEL: info');
w();
w('services:');
w('  caddy:');
w('    image: caddy:2-alpine');
w('    restart: unless-stopped');
w('    ports: ["80:80", "443:443"]');
w('    environment: { DOMAIN: "${DOMAIN}" }');
w('    volumes:');
w('      - ./Caddyfile:/etc/caddy/Caddyfile:ro');
w('      - caddy-data:/data');
w('    depends_on: [gateway]');
w('  postgres:');
w('    image: postgres:16-alpine');
w('    restart: unless-stopped');
w('    environment: { POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}" }');
w('    volumes:');
w('      - pgdata:/var/lib/postgresql/data');
w('      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro');
w('    healthcheck: { test: ["CMD", "pg_isready", "-U", "postgres"], interval: 5s, retries: 20 }');
w('  nats:');
w('    image: nats:2.12-alpine');
w('    restart: unless-stopped');
w('    command: ["-js", "-sd", "/data"]');
w('    volumes: [natsdata:/data]');
w('  redis:');
w('    image: valkey/valkey:8-alpine');
w('    restart: unless-stopped');
for (const name of NAMES) {
  w(`  ${name}:`);
  w('    <<: *service');
  w(`    image: ${IMAGE}/${name}:\${TAG}`);
  w('    environment:');
  w('      <<: *service-env');
  w(`      SERVICE_NAME: ${name}`);
  w(
    `      DATABASE_URL: postgres://${name}:\${DB_PASSWORD_${name.toUpperCase()}:-${name}}@postgres:5432/${name}`,
  );
  if (name === 'identity') {
    w('      ADMIN_EMAIL: ${ADMIN_EMAIL}');
    w('      ADMIN_PASSWORD: ${ADMIN_PASSWORD}');
    w('      COOKIE_SECURE: "true"');
    // The website (vercel.app) and the API (sslip.io) are different sites.
    w('      COOKIE_SAMESITE: none');
  }
}
w('  gateway:');
w(`    image: ${IMAGE}/gateway:\${TAG}`);
w('    restart: unless-stopped');
w('    depends_on: [identity, redis]');
w('    environment:');
w('      NODE_ENV: production');
w('      SERVICE_NAME: gateway');
w('      HOST: 0.0.0.0');
w('      PORT: "8080"');
w('      REDIS_URL: redis://redis:6379');
w('      JWKS_URL: http://identity:8080/.well-known/jwks.json');
w('      INTERNAL_TOKEN: ${INTERNAL_TOKEN}');
w('      CORS_ORIGINS: ${WEB_ORIGIN}');
for (const name of NAMES) w(`      ${name.toUpperCase()}_URL: http://${name}:8080`);
w();
w('volumes:');
w('  pgdata: {}');
w('  natsdata: {}');
w('  caddy-data: {}');
writeFileSync(join(here, 'docker-compose.yml'), `${lines.join('\n')}\n`);

writeFileSync(
  join(here, 'Caddyfile'),
  `# GENERATED by infra/vm/generate.mjs. HTTPS certificates are fetched and renewed automatically.
{$DOMAIN} {
\tencode zstd gzip
\treverse_proxy gateway:8080
}
`,
);

// Same one-database-per-service script as the compose stack, but the superuser password comes from .env.
copyFileSync(join(root, 'infra', 'compose', 'postgres-init.sh'), join(here, 'postgres-init.sh'));
console.log('wrote infra/vm/docker-compose.yml, Caddyfile, postgres-init.sh');
