/** Words for the writers' studio. Both languages, next to the screens that use them. */

/** The draft statuses in workflow order (the contract's list, kept here so screens do not load its schemas). */
export const DRAFT_STATUSES = [
  'draft',
  'in_review',
  'changes_requested',
  'approved',
  'published',
] as const;

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en = {
  status: {
    draft: 'Draft',
    in_review: 'In review',
    changes_requested: 'Changes requested',
    approved: 'Approved',
    published: 'Published',
  },
  statusAll: 'All',
  kind: { concept: 'Concept', lesson: 'Lesson', item: 'Question', misconception: 'Mistake' },
  itemType: {
    mcq: 'Multiple choice',
    'predict-output': 'Predict the output',
    'arrange-steps': 'Put in order',
    'fill-blank': 'Fill the blank',
    'trace-table': 'Trace table',
    'truth-table': 'Truth table',
  },
  op: { upsert: 'Add or change', delete: 'Delete' },
  home: {
    title: 'Studio',
    greeting: (name: string) => `Hello, ${name}`,
    subtitle: 'Write and improve lessons. An admin reviews each draft before it goes live.',
    newDraft: 'New draft',
    stats: {
      total: 'Drafts',
      review: 'Waiting for review',
      changes: 'Need changes',
      published: 'Published',
    },
    attention: 'Needs your attention',
    attentionNone: 'Nothing needs changes right now.',
    recent: 'Recent drafts',
    recentEmpty: 'You have no drafts yet. Start one to add a question or a lesson.',
    allDrafts: 'All drafts',
    live: 'Live curriculum',
    liveBody: (version: number, concepts: number, items: number) =>
      `Version ${version} · ${concepts} ${plural(concepts, 'concept', 'concepts')} · ${items} ${plural(items, 'question', 'questions')}`,
    updated: (when: string) => `Updated ${when}`,
    quick: 'Quick links',
  },
  drafts: {
    title: 'Drafts',
    filter: 'Status',
    columns: { title: 'Title', status: 'Status', changes: 'Changes', updated: 'Updated' },
    changes: (n: number) => `${n} ${plural(n, 'change', 'changes')}`,
    empty: 'No drafts here yet.',
    open: 'Open',
    caption: 'Your drafts',
  },
  create: {
    title: 'Start a new draft',
    intro:
      'A draft collects the changes you want to make. Add questions, lessons or fixes, then send it for review.',
    name: 'Draft title',
    nameHelp: 'Say what it is about, for example "Loops: three new questions".',
    submit: 'Create draft',
  },
  draft: {
    back: 'All drafts',
    rename: 'Rename',
    titleLabel: 'Title',
    saveTitle: 'Save title',
    titleSaved: 'Title saved',
    cancel: 'Cancel',
    changes: 'Changes in this draft',
    noChanges: 'No changes yet. Add a question, a lesson or a fix below.',
    add: 'Add a change',
    newItem: 'New question',
    newLesson: 'New lesson',
    newConcept: 'New concept',
    newMistake: 'New common mistake',
    editExisting: 'Change something that exists',
    deleteExisting: 'Delete something that exists',
    pick: 'Choose…',
    edit: 'Edit',
    remove: 'Remove from draft',
    removed: 'Removed from the draft',
    check: 'Check against the live curriculum',
    checking: 'Checking…',
    checkOk: 'Everything checks out.',
    checkWarn: 'Fine to send, with a few notes.',
    checkFail: 'Fix these before sending for review.',
    issues: 'Things to look at',
    submit: 'Send for review',
    submitted: 'Sent for review',
    withdraw: 'Take it back',
    withdrawn: 'Back to draft',
    delete: 'Delete draft',
    deleteTitle: 'Delete this draft?',
    deleteBody: 'The changes in it will be lost.',
    deleted: 'Draft deleted',
    activity: 'History',
    action: {
      created: 'Created',
      edited: 'Edited',
      submitted: 'Sent for review',
      withdrawn: 'Taken back',
      approved: 'Approved',
      changes_requested: 'Changes requested',
      published: 'Published',
      publish_failed: 'Publishing failed',
    },
    system: 'System',
    reviewerSays: 'The reviewer asks:',
    publishedAs: (n: number) => `Live as curriculum version ${n}.`,
    locked: 'This draft is with a reviewer. Take it back to change it.',
    readOnly: 'This draft is finished and cannot be changed.',
    needChanges: 'Add at least one change before sending it for review.',
    delChange: 'Delete',
    changeSummary: { delete: (kind: string, id: string) => `Delete ${kind} ${id}` },
  },
  editor: {
    back: 'Back to the draft',
    newTitle: (kind: string) => `New ${kind}`,
    editTitle: (kind: string, id: string) => `Edit ${kind}: ${id}`,
    save: 'Save to draft',
    saved: 'Saved to the draft',
    invalid: 'Fix the highlighted problems to save.',
    problems: 'Problems',
    preview: 'Preview',
    previewHelp: 'Try your question as a learner would. Nothing here is recorded.',
    previewNeed: 'The preview appears when the question is complete.',
    english: 'English',
    hinglish: 'Hinglish',
    id: 'ID',
    idHelp: 'Lowercase words joined by dots or dashes. It cannot change later.',
    concept: 'Concept',
    difficulty: 'Difficulty (1 easy, 5 hard)',
    seconds: 'Time it takes (seconds)',
    prompt: 'The question',
    code: 'Program shown with the question',
    codeBlank: 'Use ___ for each blank',
    hints: 'Hints (1 to 3, from gentle to strong)',
    explanation: 'Explanation shown after answering',
    why: 'A "why" check after a right answer (optional)',
    whyQuestion: 'The "why" question',
    options: 'Choices',
    optionText: 'Choice',
    correct: 'Correct',
    misconception: 'Mistake this choice shows',
    none: 'None',
    addOption: 'Add a choice',
    ask: 'What to ask for',
    askLast: 'The last thing shown',
    askAll: 'Everything shown, in order',
    answer: 'Right answer',
    wrongAnswers: 'Wrong answers that show a mistake (optional)',
    wrongMatch: 'If they answer',
    addWrong: 'Add one',
    lines: 'Program lines in the right order',
    linesHelp: 'One line per row, indentation included. Learners see them shuffled.',
    steps: 'Steps in the right order',
    stepsMode: 'What are the learners ordering?',
    modeLines: 'Program lines',
    modeSteps: 'Plain-language steps',
    expectedOutput: 'What the program shows (one line per row)',
    blanks: 'Blanks',
    blankAccept: 'Accepted answers (separate with commas)',
    columns: 'Table columns (separate with commas)',
    traceLine: 'Record a row each time this line finishes',
    rows: 'Right answers, one row per line of the table',
    inputs: 'Input names (separate with commas, up to 3)',
    outputs: 'Outputs',
    outputLabel: 'Label',
    outputExpr: 'Expression',
    truthRows: 'Expected outputs for each combination of inputs',
    addRow: 'Add a row',
    remove: 'Remove',
    minutes: 'Minutes to learn',
    storyTitle: 'Story title',
    storyBody: 'Story paragraphs (1 to 5)',
    terms: 'New words (up to 3)',
    term: 'Word',
    meaning: 'Meaning',
    addTerm: 'Add a word',
    addParagraph: 'Add a paragraph',
    seeIntro: 'Introduction to "see it run"',
    seeCode: 'Program to watch step by step',
    predictIntro: 'Introduction to "predict"',
    pauseAt: 'Pause the animation at step',
    predictItem: 'Question to predict',
    practice: 'Practice questions (1 to 8)',
    recap: 'Recap points (1 to 5)',
    addPoint: 'Add a point',
    stage: 'Stage',
    conceptTitle: 'Title',
    prerequisites: 'Learners should know these first',
    mistakeTitle: 'Name of the mistake',
    mistakeExplain: 'Why it is wrong, in plain words',
    lessonFor: 'Lesson for concept',
    chooseConcept: 'Choose the concept',
    chooseType: 'Choose a question type',
    unknownKind: 'This kind of change cannot be edited here.',
    notFound: 'That item was not found.',
    lessonPreviewTitle: 'How it reads',
    programError: (message: string) => `The program does not run yet: ${message}`,
    complexity: 'How the work grows',
  },
  media: {
    title: 'Pictures',
    intro:
      'Upload pictures to use in lessons. Every picture needs a short description for people who cannot see it.',
    file: 'Picture',
    fileHelp: 'PNG, JPEG, WebP or GIF, up to 5 MB.',
    alt: 'Describe the picture',
    altHelp: 'For example "A school gate with a counter clicker".',
    upload: 'Upload',
    uploaded: 'Picture uploaded',
    empty: 'No pictures yet.',
    delete: 'Delete',
    deleteTitle: 'Delete this picture?',
    deleteBody: 'Lessons that use it will show a gap.',
    deleted: 'Picture deleted',
    copyId: 'Copy ID',
    size: (kb: number) => `${kb} KB`,
    dimensions: (w: number, h: number) => `${w} × ${h}`,
    by: (id: string) => `Uploaded by ${id}`,
  },
  stats: {
    title: 'How questions perform',
    intro: 'See which questions learners find hard, and which mistakes they make most.',
    concept: 'Concept',
    all: 'All concepts',
    columns: {
      item: 'Question',
      attempts: 'Tries',
      firstTry: 'Right first time',
      hints: 'Hints used',
      seconds: 'Seconds',
      mistake: 'Most common mistake',
    },
    caption: 'Question statistics',
    empty: 'No answers yet. Statistics appear once learners have tried the questions.',
    hardest: 'Hardest questions',
    hardestNote: 'Share of learners who got it right on the first try',
    firstTryName: 'Right first time',
    value: 'Share',
    hintAvg: (n: number) => `${n} on average`,
  },
};

type Strings = typeof en;

const hi: Strings = {
  status: {
    draft: 'Draft',
    in_review: 'Review me',
    changes_requested: 'Badlav chahiye',
    approved: 'Approved',
    published: 'Publish ho gaya',
  },
  statusAll: 'Sab',
  kind: { concept: 'Concept', lesson: 'Lesson', item: 'Sawaal', misconception: 'Galti' },
  itemType: {
    mcq: 'Multiple choice',
    'predict-output': 'Output batao',
    'arrange-steps': 'Sahi order me lagao',
    'fill-blank': 'Khaali jagah bharo',
    'trace-table': 'Trace table',
    'truth-table': 'Truth table',
  },
  op: { upsert: 'Jodo ya badlo', delete: 'Hatao' },
  home: {
    title: 'Studio',
    greeting: (name) => `Namaste, ${name}`,
    subtitle:
      'Lessons likho aur behtar banao. Live hone se pehle har draft ko ek admin review karta hai.',
    newDraft: 'Naya draft',
    stats: {
      total: 'Drafts',
      review: 'Review ke intezaar me',
      changes: 'Badlav chahiye',
      published: 'Publish hue',
    },
    attention: 'Tumhara dhyaan chahiye',
    attentionNone: 'Abhi kisi me badlav nahi chahiye.',
    recent: 'Haal ke drafts',
    recentEmpty: 'Abhi koi draft nahi. Sawaal ya lesson jodne ke liye ek shuru karo.',
    allDrafts: 'Sabhi drafts',
    live: 'Live curriculum',
    liveBody: (version, concepts, items) =>
      `Version ${version} · ${concepts} concepts · ${items} sawaal`,
    updated: (when) => `Update: ${when}`,
    quick: 'Jaldi ke links',
  },
  drafts: {
    title: 'Drafts',
    filter: 'Status',
    columns: { title: 'Title', status: 'Status', changes: 'Badlav', updated: 'Update' },
    changes: (n) => `${n} badlav`,
    empty: 'Yahan abhi koi draft nahi.',
    open: 'Kholo',
    caption: 'Tumhare drafts',
  },
  create: {
    title: 'Naya draft shuru karo',
    intro:
      'Draft me tumhare saare badlav jama hote hain. Sawaal, lessons ya sudhar jodo, phir review ke liye bhejo.',
    name: 'Draft ka title',
    nameHelp: 'Batao yeh kis baare me hai, jaise "Loops: teen naye sawaal".',
    submit: 'Draft banao',
  },
  draft: {
    back: 'Sabhi drafts',
    rename: 'Naam badlo',
    titleLabel: 'Title',
    saveTitle: 'Title save karo',
    titleSaved: 'Title save ho gaya',
    cancel: 'Cancel',
    changes: 'Is draft ke badlav',
    noChanges: 'Abhi koi badlav nahi. Neeche se sawaal, lesson ya sudhar jodo.',
    add: 'Badlav jodo',
    newItem: 'Naya sawaal',
    newLesson: 'Naya lesson',
    newConcept: 'Naya concept',
    newMistake: 'Nayi aam galti',
    editExisting: 'Jo hai use badlo',
    deleteExisting: 'Jo hai use hatao',
    pick: 'Chuno…',
    edit: 'Badlo',
    remove: 'Draft se hatao',
    removed: 'Draft se hata diya',
    check: 'Live curriculum se check karo',
    checking: 'Check ho raha hai…',
    checkOk: 'Sab theek hai.',
    checkWarn: 'Bhej sakte ho, bas kuch notes hain.',
    checkFail: 'Review ke liye bhejne se pehle inhe theek karo.',
    issues: 'Dekhne wali baatein',
    submit: 'Review ke liye bhejo',
    submitted: 'Review ke liye bhej diya',
    withdraw: 'Wapas le lo',
    withdrawn: 'Wapas draft me',
    delete: 'Draft delete karo',
    deleteTitle: 'Yeh draft delete karna hai?',
    deleteBody: 'Isme ke saare badlav kho jaayenge.',
    deleted: 'Draft delete ho gaya',
    activity: 'Itihaas',
    action: {
      created: 'Banaya',
      edited: 'Badla',
      submitted: 'Review ke liye bheja',
      withdrawn: 'Wapas liya',
      approved: 'Approve hua',
      changes_requested: 'Badlav maange',
      published: 'Publish hua',
      publish_failed: 'Publish nahi ho paya',
    },
    system: 'System',
    reviewerSays: 'Reviewer kehte hain:',
    publishedAs: (n) => `Curriculum version ${n} ke roop me live.`,
    locked: 'Yeh draft reviewer ke paas hai. Badalne ke liye ise wapas lo.',
    readOnly: 'Yeh draft poora ho gaya aur badla nahi ja sakta.',
    needChanges: 'Review ke liye bhejne se pehle kam se kam ek badlav jodo.',
    delChange: 'Hatao',
    changeSummary: { delete: (kind, id) => `${kind} ${id} hatao` },
  },
  editor: {
    back: 'Draft par wapas',
    newTitle: (kind) => `Naya ${kind}`,
    editTitle: (kind, id) => `${kind} badlo: ${id}`,
    save: 'Draft me save karo',
    saved: 'Draft me save ho gaya',
    invalid: 'Save karne ke liye dikhaaye gaye problems theek karo.',
    problems: 'Problems',
    preview: 'Preview',
    previewHelp: 'Apna sawaal learner ki tarah try karo. Yahan kuch record nahi hota.',
    previewNeed: 'Sawaal poora hote hi preview dikhega.',
    english: 'English',
    hinglish: 'Hinglish',
    id: 'ID',
    idHelp: 'Chhote akshar, dots ya dash se jude. Baad me badal nahi sakta.',
    concept: 'Concept',
    difficulty: 'Mushkil level (1 aasaan, 5 mushkil)',
    seconds: 'Kitna time lagta hai (seconds)',
    prompt: 'Sawaal',
    code: 'Sawaal ke saath dikhne wala program',
    codeBlank: 'Har khaali jagah ke liye ___ likho',
    hints: 'Hints (1 se 3, halke se mazboot)',
    explanation: 'Jawab ke baad dikhne wali explanation',
    why: 'Sahi jawab ke baad "kyun" check (optional)',
    whyQuestion: '"Kyun" ka sawaal',
    options: 'Options',
    optionText: 'Option',
    correct: 'Sahi',
    misconception: 'Yeh option kaunsi galti dikhata hai',
    none: 'Koi nahi',
    addOption: 'Option jodo',
    ask: 'Kya poochna hai',
    askLast: 'Aakhri jo dikhe',
    askAll: 'Jo kuch dikhe, order me',
    answer: 'Sahi jawab',
    wrongAnswers: 'Galat jawab jo koi galti dikhate hain (optional)',
    wrongMatch: 'Agar jawab ho',
    addWrong: 'Ek jodo',
    lines: 'Program ki lines, sahi order me',
    linesHelp: 'Ek row me ek line, indentation ke saath. Learners ko woh mix hokar dikhti hain.',
    steps: 'Steps, sahi order me',
    stepsMode: 'Learners kya order me lagayenge?',
    modeLines: 'Program ki lines',
    modeSteps: 'Aasaan bhasha ke steps',
    expectedOutput: 'Program kya dikhata hai (ek row me ek line)',
    blanks: 'Khaali jagahein',
    blankAccept: 'Maanye jawab (comma se alag karo)',
    columns: 'Table ke columns (comma se alag karo)',
    traceLine: 'Jab yeh line khatam ho tab ek row likho',
    rows: 'Sahi jawab, table ki har line ke liye ek row',
    inputs: 'Input ke naam (comma se alag, 3 tak)',
    outputs: 'Outputs',
    outputLabel: 'Label',
    outputExpr: 'Expression',
    truthRows: 'Inputs ke har combination ke liye expected output',
    addRow: 'Row jodo',
    remove: 'Hatao',
    minutes: 'Seekhne ke minute',
    storyTitle: 'Kahani ka title',
    storyBody: 'Kahani ke paragraphs (1 se 5)',
    terms: 'Naye shabd (3 tak)',
    term: 'Shabd',
    meaning: 'Matlab',
    addTerm: 'Shabd jodo',
    addParagraph: 'Paragraph jodo',
    seeIntro: '"Chalta hua dekho" ka parichay',
    seeCode: 'Step-by-step dekhne wala program',
    predictIntro: '"Predict" ka parichay',
    pauseAt: 'Animation is step par roko',
    predictItem: 'Predict karne wala sawaal',
    practice: 'Practice sawaal (1 se 8)',
    recap: 'Recap ke points (1 se 5)',
    addPoint: 'Point jodo',
    stage: 'Stage',
    conceptTitle: 'Title',
    prerequisites: 'Learners ko pehle yeh aana chahiye',
    mistakeTitle: 'Galti ka naam',
    mistakeExplain: 'Yeh galat kyun hai, aasaan shabdon me',
    lessonFor: 'Is concept ka lesson',
    chooseConcept: 'Concept chuno',
    chooseType: 'Sawaal ka type chuno',
    unknownKind: 'Is tarah ka badlav yahan nahi badla ja sakta.',
    notFound: 'Woh cheez nahi mili.',
    lessonPreviewTitle: 'Aisa padhega',
    programError: (message: string) => `Program abhi nahi chalta: ${message}`,
    complexity: 'Kaam kitna badhta hai',
  },
  media: {
    title: 'Tasveerein',
    intro:
      'Lessons me use karne ke liye tasveerein upload karo. Har tasveer ka chhota description zaroori hai, un logon ke liye jo dekh nahi sakte.',
    file: 'Tasveer',
    fileHelp: 'PNG, JPEG, WebP ya GIF, 5 MB tak.',
    alt: 'Tasveer ka description',
    altHelp: 'Jaise "School gate aur counter clicker".',
    upload: 'Upload karo',
    uploaded: 'Tasveer upload ho gayi',
    empty: 'Abhi koi tasveer nahi.',
    delete: 'Hatao',
    deleteTitle: 'Yeh tasveer hatani hai?',
    deleteBody: 'Jin lessons me yeh hai wahan khaali jagah dikhegi.',
    deleted: 'Tasveer hat gayi',
    copyId: 'ID copy karo',
    size: (kb) => `${kb} KB`,
    dimensions: (w, h) => `${w} × ${h}`,
    by: (id) => `${id} ne upload ki`,
  },
  stats: {
    title: 'Sawaal kaisa kaam kar rahe hain',
    intro:
      'Dekho learners ko kaunse sawaal mushkil lagte hain aur kaunsi galtiyan sabse zyada hoti hain.',
    concept: 'Concept',
    all: 'Sabhi concepts',
    columns: {
      item: 'Sawaal',
      attempts: 'Koshishein',
      firstTry: 'Pehli baar sahi',
      hints: 'Hints',
      seconds: 'Seconds',
      mistake: 'Sabse aam galti',
    },
    caption: 'Sawaalon ke stats',
    empty: 'Abhi koi jawab nahi. Learners ke try karte hi stats dikhenge.',
    hardest: 'Sabse mushkil sawaal',
    hardestNote: 'Kitne learners ne pehli baar me sahi kiya',
    firstTryName: 'Pehli baar sahi',
    value: 'Hissa',
    hintAvg: (n) => `Aaushat ${n}`,
  },
};

export const studioStrings = { en, 'hi-Latn': hi };
