#!/usr/bin/env node
// Writes infra/compose/docker-compose.yml from the service list in infra/dev/services.mjs, so
// the compose file, the native stack runner and the gateway never disagree about services.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICES } from '../dev/services.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const lines = [];
const w = (s = '') => lines.push(s);

w('# GENERATED by infra/compose/generate.mjs. Do not edit by hand.');
w('# Run everything:   docker compose -f infra/compose/docker-compose.yml up --build');
w('# With tracing/metrics: add `--profile observability`.');
w('name: logicpath');
w();
w('x-service: &service');
w('  build:');
w('    context: ../..');
w('    dockerfile: infra/docker/service.Dockerfile');
w('  restart: unless-stopped');
w('  depends_on:');
w('    postgres: { condition: service_healthy }');
w('    nats: { condition: service_started }');
w('  environment: &service-env');
w('    HOST: 0.0.0.0');
w('    PORT: "8080"');
w('    NATS_URL: nats://nats:4222');
w('    JWKS_URL: http://identity:8080/.well-known/jwks.json');
w('    CONTENT_URL: http://content:8080');
w('    SMTP_URL: smtp://mailpit:1025');
w('    PUBLIC_WEB_URL: http://localhost:3000');
w('    INTERNAL_TOKEN: ${INTERNAL_TOKEN:-dev-internal-token-change-me}');
w('    LOG_LEVEL: info');
w();
w('services:');
w('  postgres:');
w('    image: postgres:16-alpine');
w('    environment: { POSTGRES_PASSWORD: postgres }');
w('    volumes:');
w('      - pgdata:/var/lib/postgresql/data');
w('      - ./postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro');
w('    healthcheck: { test: ["CMD", "pg_isready", "-U", "postgres"], interval: 5s, retries: 20 }');
w('  nats:');
w('    image: nats:2.12-alpine');
w('    command: ["-js", "-sd", "/data", "-m", "8222"]');
w('    volumes: [natsdata:/data]');
w('  redis:');
w('    image: valkey/valkey:8-alpine');
w('  mailpit:');
w('    image: axllent/mailpit:latest');
w('    ports: ["8025:8025"]');
for (const name of Object.keys(SERVICES)) {
  w(`  ${name}:`);
  w('    <<: *service');
  w('    build:');
  w('      context: ../..');
  w('      dockerfile: infra/docker/service.Dockerfile');
  w(`      args: { SERVICE: ${name} }`);
  w('    environment:');
  w('      <<: *service-env');
  w(`      SERVICE_NAME: ${name}`);
  w(`      DATABASE_URL: postgres://${name}:${name}@postgres:5432/${name}`);
  if (name === 'identity') {
    w('      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@logicpath.dev}');
    w('      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin-password-1}');
    w('      COOKIE_SECURE: "false"');
  }
}
w('  gateway:');
w('    build:');
w('      context: ../..');
w('      dockerfile: infra/docker/service.Dockerfile');
w('      args: { SERVICE: gateway }');
w('    restart: unless-stopped');
w('    ports: ["8080:8080"]');
w('    depends_on: [identity, redis]');
w('    environment:');
w('      SERVICE_NAME: gateway');
w('      HOST: 0.0.0.0');
w('      PORT: "8080"');
w('      REDIS_URL: redis://redis:6379');
w('      CORS_ORIGINS: http://localhost:3000');
for (const name of Object.keys(SERVICES)) w(`      ${name.toUpperCase()}_URL: http://${name}:8080`);
w('  web:');
w('    build:');
w('      context: ../..');
w('      dockerfile: infra/docker/web.Dockerfile');
w('    ports: ["3000:3000"]');
w('    environment:');
w('      NEXT_PUBLIC_API_URL: http://localhost:8080');
w('    depends_on: [gateway]');
w('  otel-collector:');
w('    image: otel/opentelemetry-collector-contrib:latest');
w('    profiles: [observability]');
w('    volumes: [./otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro]');
w('  jaeger:');
w('    image: jaegertracing/jaeger:latest');
w('    profiles: [observability]');
w('    ports: ["16686:16686"]');
w('  prometheus:');
w('    image: prom/prometheus:latest');
w('    profiles: [observability]');
w('    volumes: [./prometheus.yml:/etc/prometheus/prometheus.yml:ro]');
w('    ports: ["9090:9090"]');
w('  grafana:');
w('    image: grafana/grafana:latest');
w('    profiles: [observability]');
w('    ports: ["3001:3000"]');
w();
w('volumes:');
w('  pgdata: {}');
w('  natsdata: {}');

writeFileSync(join(here, 'docker-compose.yml'), `${lines.join('\n')}\n`);

// Prometheus scrapes every service's /metrics.
const scrape = [
  'global: { scrape_interval: 15s }',
  'scrape_configs:',
  '  - job_name: logicpath',
  '    static_configs:',
  `      - targets: [${[...Object.keys(SERVICES), 'gateway'].map((n) => `"${n}:8080"`).join(', ')}]`,
];
writeFileSync(join(here, 'prometheus.yml'), `${scrape.join('\n')}\n`);
console.log('wrote docker-compose.yml and prometheus.yml');
