#!/usr/bin/env node
// Writes render.yaml (Render Blueprint) from infra/dev/services.mjs: every service as a private
// service running the image CD pushed to GHCR, NATS with a disk, Render Key Value for Redis,
// and the gateway and website as the public web services. See docs/cicd.md for first-time setup.
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SERVICES } from '../dev/services.mjs';

const root = new URL('../..', import.meta.url).pathname;
const REGISTRY = 'ghcr.io/abhayvaishnav09/dsa-learning';
const NAMES = Object.keys(SERVICES).filter((n) =>
  existsSync(join(root, 'services', n, 'src', 'main.ts')),
);

const lines = [
  '# GENERATED by infra/render/generate.mjs. Do not edit by hand.',
  '# Render Blueprint: New → Blueprint → pick this repo. CD then redeploys with RENDER_DEPLOY_HOOKS.',
  'envVarGroups:',
  '  - name: logicpath-shared',
  '    envVars:',
  '      - { key: INTERNAL_TOKEN, generateValue: true }',
  '      - { key: NATS_URL, value: "nats://nats:4222" }',
  '      - { key: JWKS_URL, value: "http://identity:8080/.well-known/jwks.json" }',
  '      - { key: CONTENT_URL, value: "http://content:8080" }',
  '      - { key: AUTHORING_URL, value: "http://authoring:8080" }',
  '      - { key: HOST, value: "0.0.0.0" }',
  '      - { key: PORT, value: "8080" }',
  '      - { key: LOG_LEVEL, value: info }',
  'services:',
  '  - type: pserv',
  '    name: nats',
  '    runtime: image',
  '    image: { url: "docker.io/library/nats:2.12-alpine" }',
  '    dockerCommand: nats-server -js -sd /data',
  '    plan: starter',
  '    disk: { name: nats-data, mountPath: /data, sizeGB: 1 }',
  '  - type: keyvalue',
  '    name: cache',
  '    plan: starter',
  '    ipAllowList: []',
];
for (const name of NAMES) {
  lines.push(
    '  - type: pserv',
    `    name: ${name}`,
    '    runtime: image',
    `    image: { url: "${REGISTRY}/${name}:main" }`,
    '    plan: starter',
    '    envVars:',
    '      - fromGroup: logicpath-shared',
    `      - { key: SERVICE_NAME, value: ${name} }`,
    '      # One database per service (ADR-0011); create them with infra/compose/postgres-init.sh.',
    '      - { key: DATABASE_URL, sync: false }',
  );
  if (name === 'identity') {
    lines.push(
      '      - { key: ADMIN_EMAIL, sync: false }',
      '      - { key: ADMIN_PASSWORD, sync: false }',
    );
  }
}
lines.push(
  '  - type: web',
  '    name: gateway',
  '    runtime: image',
  `    image: { url: "${REGISTRY}/gateway:main" }`,
  '    plan: starter',
  '    healthCheckPath: /healthz',
  '    envVars:',
  '      - fromGroup: logicpath-shared',
  '      - { key: SERVICE_NAME, value: gateway }',
  '      - key: REDIS_URL',
  '        fromService: { type: keyvalue, name: cache, property: connectionString }',
  '      - { key: CORS_ORIGINS, sync: false }',
  ...NAMES.map((n) => `      - { key: ${n.toUpperCase()}_URL, value: "http://${n}:8080" }`),
  '  - type: web',
  '    name: web',
  '    runtime: image',
  `    image: { url: "${REGISTRY}/web:main" }`,
  '    plan: starter',
  '    healthCheckPath: /',
  '    envVars:',
  '      - { key: PORT, value: "3000" }',
);
writeFileSync(join(root, 'render.yaml'), `${lines.join('\n')}\n`);
console.log(`wrote render.yaml (${NAMES.length} services + gateway + web)`);
