#!/usr/bin/env node
// Writes the Kubernetes manifests (kustomize) from the service list in infra/dev/services.mjs,
// like the compose generator, so compose, k8s and the gateway always agree on services.
//   base/                      every service + gateway + web, hardened, with probes and autoscaling
//   overlays/staging/          1 replica, in-cluster Postgres, staging host
//   overlays/production/       2+ replicas, external Postgres, production host
// Validate: kustomize build overlays/staging | kubeconform -strict -summary
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SERVICES } from '../dev/services.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
export const REGISTRY = 'ghcr.io/abhayvaishnav09/dsa-learning';
const NAMES = Object.keys(SERVICES).filter((name) =>
  existsSync(join(root, 'services', name, 'src', 'main.ts')),
);

const write = (path, text) => {
  mkdirSync(dirname(join(here, path)), { recursive: true });
  writeFileSync(
    join(here, path),
    `# GENERATED by infra/k8s/generate.mjs. Do not edit by hand.\n${text.trimStart()}`,
  );
};

/** The two standard labels, the second indented to match the first. */
const labels = (name, indent = 4) =>
  `app.kubernetes.io/name: ${name}\n${' '.repeat(indent)}app.kubernetes.io/part-of: logicpath`;

const securityContext = `securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ALL] }`;

function deployment(
  name,
  { port, env, probePath = '/healthz', readyPath = '/readyz', cpu = '100m', memory = '192Mi' },
) {
  return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  labels:
    ${labels(name)}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
  strategy:
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
  template:
    metadata:
      labels:
        ${labels(name, 8)}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "${port}"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile: { type: RuntimeDefault }
      terminationGracePeriodSeconds: 30
      containers:
        - name: ${name}
          image: ${REGISTRY}/${name}:latest
          ports: [{ name: http, containerPort: ${port} }]
          envFrom: [{ configMapRef: { name: logicpath-config } }]
          env:
${env.map((e) => `            ${e}`).join('\n')}
          readinessProbe:
            httpGet: { path: ${readyPath}, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: ${probePath}, port: http }
            initialDelaySeconds: 20
            periodSeconds: 10
          startupProbe:
            httpGet: { path: ${probePath}, port: http }
            failureThreshold: 30
            periodSeconds: 2
          resources:
            requests: { cpu: ${cpu}, memory: ${memory} }
            limits: { memory: 512Mi }
          ${securityContext}
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
      volumes: [{ name: tmp, emptyDir: {} }]
---
apiVersion: v1
kind: Service
metadata:
  name: ${name}
  labels:
    ${labels(name)}
spec:
  selector:
    app.kubernetes.io/name: ${name}
  ports: [{ name: http, port: ${port === 3000 ? 3000 : 8080}, targetPort: http }]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: ${name} }
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${name}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}
`;
}

const secretEnv = (name, secret, key) =>
  `- name: ${name}\n              valueFrom: { secretKeyRef: { name: ${secret}, key: ${key} } }`;

const files = [];
for (const name of NAMES) {
  const env = [
    `- { name: SERVICE_NAME, value: ${name} }`,
    secretEnv('DATABASE_URL', 'logicpath-db', name),
    secretEnv('INTERNAL_TOKEN', 'logicpath-secrets', 'internal-token'),
  ];
  if (name === 'identity') {
    env.push(
      secretEnv('ADMIN_EMAIL', 'logicpath-secrets', 'admin-email'),
      secretEnv('ADMIN_PASSWORD', 'logicpath-secrets', 'admin-password'),
    );
  }
  write(`base/services/${name}.yaml`, deployment(name, { port: 8080, env }));
  files.push(`services/${name}.yaml`);
}

write(
  'base/services/gateway.yaml',
  deployment('gateway', {
    port: 8080,
    readyPath: '/healthz',
    env: [
      `- { name: SERVICE_NAME, value: gateway }`,
      `- { name: REDIS_URL, value: "redis://redis:6379" }`,
      secretEnv('INTERNAL_TOKEN', 'logicpath-secrets', 'internal-token'),
      ...NAMES.map((n) => `- { name: ${n.toUpperCase()}_URL, value: "http://${n}:8080" }`),
    ],
  }),
);
files.push('services/gateway.yaml');

write(
  'base/services/web.yaml',
  deployment('web', {
    port: 3000,
    env: ['- { name: PORT, value: "3000" }'],
    probePath: '/',
    readyPath: '/',
    cpu: '100m',
    memory: '256Mi',
  }),
);
files.push('services/web.yaml');

write(
  'base/config.yaml',
  `apiVersion: v1
kind: ConfigMap
metadata:
  name: logicpath-config
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  LOG_LEVEL: info
  NATS_URL: nats://nats:4222
  JWKS_URL: http://identity:8080/.well-known/jwks.json
${NAMES.map((n) => `  ${n.toUpperCase()}_URL: http://${n}:8080`).join('\n')}
  SMTP_URL: smtp://mail:1025
  PUBLIC_WEB_URL: https://logicpath.dev
  PUBLIC_API_URL: https://api.logicpath.dev
`,
);

write(
  'base/nats.yaml',
  `apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  labels:
    ${labels('nats')}
spec:
  serviceName: nats
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  template:
    metadata:
      labels:
        ${labels('nats', 8)}
    spec:
      containers:
        - name: nats
          image: nats:2.12-alpine
          args: ["-js", "-sd", "/data", "-m", "8222"]
          ports: [{ name: client, containerPort: 4222 }, { name: monitor, containerPort: 8222 }]
          readinessProbe: { httpGet: { path: /healthz, port: monitor } }
          resources: { requests: { cpu: 50m, memory: 128Mi }, limits: { memory: 512Mi } }
          volumeMounts: [{ name: data, mountPath: /data }]
  volumeClaimTemplates:
    - metadata: { name: data }
      spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 2Gi } } }
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app.kubernetes.io/name: nats
  ports: [{ name: client, port: 4222, targetPort: client }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    ${labels('redis')}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        ${labels('redis', 8)}
    spec:
      containers:
        - name: redis
          image: valkey/valkey:8-alpine
          ports: [{ name: redis, containerPort: 6379 }]
          readinessProbe: { tcpSocket: { port: redis } }
          resources: { requests: { cpu: 25m, memory: 64Mi }, limits: { memory: 256Mi } }
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app.kubernetes.io/name: redis
  ports: [{ name: redis, port: 6379, targetPort: redis }]
`,
);

write(
  'base/ingress.yaml',
  `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logicpath
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: logicpath.example
      http:
        paths:
${['/v1', '/public', '/.well-known', '/media']
  .map(
    (p) =>
      `          - { path: ${p}, pathType: Prefix, backend: { service: { name: gateway, port: { number: 8080 } } } }`,
  )
  .join('\n')}
          - { path: /, pathType: Prefix, backend: { service: { name: web, port: { number: 3000 } } } }
`,
);

write(
  'base/network-policy.yaml',
  `# Only pods in this namespace (and the ingress controller) may talk to the services.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: same-namespace-only
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: ingress-nginx }
`,
);

write(
  'base/kustomization.yaml',
  `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs: { app.kubernetes.io/part-of: logicpath }
resources:
  - config.yaml
  - nats.yaml
  - ingress.yaml
  - network-policy.yaml
${files.map((f) => `  - ${f}`).join('\n')}
images:
${[...NAMES, 'gateway', 'web'].map((n) => `  - { name: ${REGISTRY}/${n}, newTag: latest }`).join('\n')}
`,
);

// Staging: one of everything, Postgres inside the cluster, created per service by the init script.
const initScript = readFileSync(join(root, 'infra', 'compose', 'postgres-init.sh'), 'utf8');
write(
  'overlays/staging/postgres.yaml',
  `apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sh: |
${initScript
  .split('\n')
  .map((l) => (l ? `    ${l}` : ''))
  .join('\n')}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: logicpath-secrets, key: postgres-password } }
            - { name: PGDATA, value: /var/lib/postgresql/data/pgdata }
          ports: [{ name: postgres, containerPort: 5432 }]
          readinessProbe: { exec: { command: [pg_isready, -U, postgres] } }
          resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { memory: 1Gi } }
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
            - { name: init, mountPath: /docker-entrypoint-initdb.d }
      volumes: [{ name: init, configMap: { name: postgres-init } }]
  volumeClaimTemplates:
    - metadata: { name: data }
      spec: { accessModes: [ReadWriteOnce], resources: { requests: { storage: 10Gi } } }
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports: [{ name: postgres, port: 5432, targetPort: postgres }]
`,
);

write(
  'overlays/staging/kustomization.yaml',
  `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logicpath-staging
resources:
  - ../../base
  - postgres.yaml
patches:
  - target: { kind: Ingress, name: logicpath }
    patch: |
      - { op: replace, path: /spec/rules/0/host, value: staging.logicpath.dev }
  - target: { kind: ConfigMap, name: logicpath-config }
    patch: |
      - { op: replace, path: /data/PUBLIC_WEB_URL, value: "https://staging.logicpath.dev" }
      - { op: replace, path: /data/LOG_LEVEL, value: debug }
# CD sets the image tags: kustomize edit set image ${REGISTRY}/<service>=…:<sha>
images:
${[...NAMES, 'gateway', 'web'].map((n) => `  - { name: ${REGISTRY}/${n}, newTag: main }`).join('\n')}
`,
);

write(
  'overlays/production/kustomization.yaml',
  `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logicpath
resources:
  - ../../base
patches:
  # Two of everything, more under load; managed Postgres comes from the logicpath-db secret.
  - target: { kind: Deployment, labelSelector: "app.kubernetes.io/part-of=logicpath" }
    patch: |
      - { op: replace, path: /spec/replicas, value: 2 }
  # Redis holds shared counters (rate limits): one instance, or use a managed one.
  - target: { kind: Deployment, name: redis }
    patch: |
      - { op: replace, path: /spec/replicas, value: 1 }
  - target: { kind: HorizontalPodAutoscaler }
    patch: |
      - { op: replace, path: /spec/minReplicas, value: 2 }
      - { op: replace, path: /spec/maxReplicas, value: 10 }
  - target: { kind: Ingress, name: logicpath }
    patch: |
      - { op: replace, path: /spec/rules/0/host, value: logicpath.dev }
images:
${[...NAMES, 'gateway', 'web'].map((n) => `  - { name: ${REGISTRY}/${n}, newTag: latest }`).join('\n')}
`,
);

console.log(`wrote infra/k8s (${NAMES.length} services + gateway + web)`);
