/** Words for the admin area. Both languages, next to the screens that use them. */

const plural = (n: number, one: string, many: string) => (n === 1 ? one : many);

const en = {
  common: {
    cancel: 'Cancel',
    save: 'Save',
    saved: 'Saved',
    delete: 'Delete',
    create: 'Create',
    edit: 'Edit',
    open: 'Open',
    copy: 'Copy',
    copied: 'Copied',
    showMore: 'Show more',
    refine: 'Showing the first 100. Narrow the search to see others.',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    none: 'None',
    system: 'System',
    you: 'you',
  },
  overview: {
    title: 'Overview',
    intro: 'How learning is going, and what needs a decision.',
    range: 'Time range',
    days: (n: number) => `Last ${n} days`,
    activeDay: 'Active today',
    activeWeek: 'Active this week',
    activeMonth: 'Active this month',
    activeNote: 'Learners who answered a question',
    pending: 'Waiting for review',
    pendingOpen: 'Open the queue',
    live: 'Live curriculum',
    liveBody: (n: number, items: number) => `Version ${n} · ${items} questions`,
    attempts: 'Answers per day',
    attemptsSeries: 'Answers',
    signups: 'New learners per day',
    signupsSeries: 'New learners',
    correct: 'Right answers',
    correctNote: 'Share of answers that were right',
    correctSeries: 'Right answers',
    lessons: 'Lessons finished per day',
    lessonsSeries: 'Lessons finished',
    mistakes: 'Most common mistakes',
    mistakesNote: 'How often each mistake was made',
    mistakesSeries: 'Times made',
    mistakesEmpty: 'No mistakes recorded in this period.',
    hardest: 'Hardest questions',
    hardestNote: 'Share of learners who got it right on the first try',
    hardestSeries: 'Right first time',
    hardestEmpty: 'Questions appear here once at least three learners have tried them.',
    date: 'Date',
    value: 'Value',
    name: 'Name',
    count: 'Count',
    demoNote:
      'The demo adds practice from made-up learners so these charts have something to show.',
  },
  review: {
    title: 'Review queue',
    intro: 'Drafts from writers, waiting for a decision.',
    filter: 'Status',
    caption: 'Submissions',
    columns: {
      title: 'Title',
      author: 'Writer',
      changes: 'Changes',
      submitted: 'Sent',
      status: 'Status',
    },
    changes: (n: number) => `${n} ${plural(n, 'change', 'changes')}`,
    empty: 'Nothing is waiting. Nice.',
    waiting: 'Waiting',
  },
  submission: {
    back: 'Review queue',
    by: (name: string) => `By ${name}`,
    changes: 'Changes',
    diff: 'What is different',
    isNew: 'New',
    removes: 'Removes this from the curriculum',
    unchanged: 'No difference from what is live.',
    before: 'Now',
    after: 'After',
    issues: 'Checks',
    activity: 'History',
    approve: 'Approve and publish',
    approveTitle: 'Approve and publish?',
    approveBody: 'The changes go live for every learner straight away.',
    comment: 'Comment (optional)',
    approved: 'Approved and published',
    requestChanges: 'Ask for changes',
    requestTitle: 'Ask the writer for changes',
    requestBody: 'Say what should be different. The writer sees this note.',
    requestComment: 'What needs to change',
    sentBack: 'Sent back to the writer',
    notReady: 'This submission is not waiting for a decision.',
    publishedAs: (n: number) => `Published as curriculum version ${n}.`,
    kind: { concept: 'Concept', lesson: 'Lesson', item: 'Question', misconception: 'Mistake' },
    action: {
      created: 'Created',
      edited: 'Edited',
      submitted: 'Sent for review',
      withdrawn: 'Taken back',
      approved: 'Approved',
      changes_requested: 'Changes requested',
      published: 'Published',
      publish_failed: 'Publishing failed',
    },
  },
  content: {
    title: 'Content versions',
    intro: 'Every publish creates a version. Roll back to an earlier one if something goes wrong.',
    live: 'Live now',
    columns: { version: 'Version', note: 'What changed', published: 'Published', status: 'Status' },
    caption: 'Content versions',
    current: 'Live',
    rollback: 'Roll back to this',
    rollbackTitle: (n: number) => `Roll back to version ${n}?`,
    rollbackBody: 'Learners get this version straight away. The newer versions stay in the list.',
    note: 'Why (optional)',
    done: 'Rolled back',
    stats: (concepts: number, items: number) =>
      `${concepts} ${plural(concepts, 'concept', 'concepts')} · ${items} ${plural(items, 'question', 'questions')}`,
  },
  users: {
    title: 'Users',
    intro: 'Find people, give writers their role, and suspend accounts.',
    search: 'Search by name or email',
    role: 'Role',
    status: 'Status',
    caption: 'Users',
    columns: { name: 'Name', email: 'Email', role: 'Role', status: 'Status', joined: 'Joined' },
    roles: { student: 'Student', writer: 'Content writer', admin: 'Admin' },
    statuses: { active: 'Active', pending_consent: 'Waiting for parent', suspended: 'Suspended' },
    empty: 'No one matches.',
    create: 'Add a user',
    createTitle: 'Add a user',
    name: 'Name',
    email: 'Email',
    password: 'Temporary password',
    passwordHelp: 'At least 8 characters. They can change it from Forgot password.',
    created: 'User created',
  },
  user: {
    back: 'All users',
    account: 'Account',
    verified: 'Email verified',
    unverified: 'Email not verified',
    joined: (date: string) => `Joined ${date}`,
    role: 'Role',
    saveRole: 'Change role',
    suspend: 'Suspend',
    reactivate: 'Reactivate',
    suspendTitle: 'Suspend this account?',
    suspendBody: 'They are signed out everywhere and cannot sign in until you reactivate them.',
    updated: 'Account updated',
    self: 'This is your own account. Someone else has to change it.',
    pending: 'Waiting for a parent to approve. Their status changes when the parent answers.',
    consent: 'Parental consent',
    consentRow: (email: string, status: string) => `Asked ${email}: ${status}`,
    trail: 'Recent changes to this account',
    trailEmpty: 'Nothing recorded yet.',
  },
  classes: {
    title: 'Classes',
    intro: 'Every class, who runs it, and its join code.',
    caption: 'Classes',
    columns: {
      name: 'Class',
      code: 'Join code',
      teacher: 'Teacher',
      members: 'Learners',
      created: 'Created',
    },
    create: 'New class',
    createTitle: 'Create a class',
    name: 'Class name',
    teacher: 'Who runs it',
    created: 'Class created',
    newCode: 'New code',
    newCodeDone: 'The old code no longer works',
    delete: 'Delete',
    deleteTitle: 'Delete this class?',
    deleteBody: 'Learners leave the class. Their own progress is not touched.',
    deleted: 'Class deleted',
    roster: 'Roster',
    empty: 'No classes yet.',
  },
  flags: {
    title: 'Feature flags',
    intro: 'Turn things on for some people or everyone, without a new release.',
    caption: 'Flags',
    columns: { key: 'Flag', on: 'On', rollout: 'Rollout', who: 'For', updated: 'Changed' },
    everyone: 'Everyone',
    create: 'New flag',
    createTitle: 'New flag',
    editTitle: (key: string) => `Edit ${key}`,
    key: 'Key',
    keyHelp: 'Lowercase words joined by dots or dashes, for example map.3d',
    description: 'What it does',
    enabled: 'Enabled',
    rollout: 'Share of people who get it (%)',
    roles: 'Only for these roles (none means everyone)',
    platforms: 'Only on these platforms (none means all)',
    minVersion: 'Lowest app version (optional)',
    value: 'Value returned when on (JSON, optional)',
    valueBad: 'That is not valid JSON.',
    saved: 'Flag saved',
    delete: 'Delete',
    deleteTitle: 'Delete this flag?',
    deleteBody: 'Apps that ask for it will treat it as off.',
    deleted: 'Flag deleted',
    roleNames: { student: 'Student', writer: 'Writer', admin: 'Admin' },
    platformNames: { web: 'Web', android: 'Android' },
    empty: 'No flags yet.',
  },
  keys: {
    title: 'API keys',
    intro:
      'Every key developers created for the public API. Change a plan, or revoke a key that is misused.',
    caption: 'API keys',
    columns: {
      name: 'Name',
      key: 'Key',
      owner: 'Owner',
      plan: 'Plan',
      quota: 'Daily limit',
      today: 'Today',
      status: 'Status',
    },
    plans: { free: 'Free', partner: 'Partner' },
    active: 'Active',
    revoked: 'Revoked',
    edit: 'Change plan',
    editTitle: (name: string) => `Change plan for ${name}`,
    plan: 'Plan',
    quota: 'Requests per day',
    saved: 'Key updated',
    revoke: 'Revoke',
    revokeTitle: 'Revoke this key?',
    revokeBody: 'Apps that use it stop working right away.',
    revokedDone: 'Key revoked',
    empty: 'Nobody has created a key yet.',
  },
  audit: {
    title: 'Audit log',
    intro: 'Who changed what, and when. Entries cannot be edited.',
    caption: 'Audit log',
    columns: { when: 'When', who: 'Who', action: 'Action', target: 'Target', details: 'Details' },
    action: 'Action',
    target: 'Target type',
    anyAction: 'Any action',
    anyTarget: 'Anything',
    system: 'System',
    empty: 'No entries match.',
    show: 'Show',
  },
  media: { title: 'Pictures' },
};

type Strings = typeof en;

const hi: Strings = {
  common: {
    cancel: 'Cancel',
    save: 'Save karo',
    saved: 'Save ho gaya',
    delete: 'Delete karo',
    create: 'Banao',
    edit: 'Badlo',
    open: 'Kholo',
    copy: 'Copy karo',
    copied: 'Copy ho gaya',
    showMore: 'Aur dikhao',
    refine: 'Pehle 100 dikha rahe hain. Baaki dekhne ke liye search chhota karo.',
    all: 'Sab',
    yes: 'Haan',
    no: 'Nahi',
    none: 'Koi nahi',
    system: 'System',
    you: 'aap',
  },
  overview: {
    title: 'Overview',
    intro: 'Seekhna kaisa chal raha hai, aur kahan faisle chahiye.',
    range: 'Samay seema',
    days: (n) => `Pichhle ${n} din`,
    activeDay: 'Aaj active',
    activeWeek: 'Is hafte active',
    activeMonth: 'Is mahine active',
    activeNote: 'Jinhone koi sawaal solve kiya',
    pending: 'Review ke intezaar me',
    pendingOpen: 'Queue kholo',
    live: 'Live curriculum',
    liveBody: (n, items) => `Version ${n} · ${items} sawaal`,
    attempts: 'Roz ke jawab',
    attemptsSeries: 'Jawab',
    signups: 'Roz ke naye learners',
    signupsSeries: 'Naye learners',
    correct: 'Sahi jawab',
    correctNote: 'Kitne jawab sahi the',
    correctSeries: 'Sahi jawab',
    lessons: 'Roz poore hue lessons',
    lessonsSeries: 'Poore lessons',
    mistakes: 'Sabse aam galtiyan',
    mistakesNote: 'Har galti kitni baar hui',
    mistakesSeries: 'Kitni baar',
    mistakesEmpty: 'Is samay me koi galti record nahi hui.',
    hardest: 'Sabse mushkil sawaal',
    hardestNote: 'Kitne learners ne pehli baar me sahi kiya',
    hardestSeries: 'Pehli baar sahi',
    hardestEmpty: 'Kam se kam teen learners ke try karne par sawaal yahan dikhenge.',
    date: 'Tareekh',
    value: 'Value',
    name: 'Naam',
    count: 'Ginti',
    demoNote: 'Demo me made-up learners ka practice jodta hai taaki in charts me kuch dikhe.',
  },
  review: {
    title: 'Review queue',
    intro: 'Writers ke drafts, faisle ke intezaar me.',
    filter: 'Status',
    caption: 'Submissions',
    columns: {
      title: 'Title',
      author: 'Writer',
      changes: 'Badlav',
      submitted: 'Bheja',
      status: 'Status',
    },
    changes: (n) => `${n} badlav`,
    empty: 'Kuch intezaar me nahi hai. Badhiya.',
    waiting: 'Intezaar me',
  },
  submission: {
    back: 'Review queue',
    by: (name) => `${name} ne likha`,
    changes: 'Badlav',
    diff: 'Kya alag hai',
    isNew: 'Naya',
    removes: 'Isse curriculum se hata deta hai',
    unchanged: 'Live se koi farq nahi.',
    before: 'Abhi',
    after: 'Baad me',
    issues: 'Checks',
    activity: 'Itihaas',
    approve: 'Approve karo aur publish karo',
    approveTitle: 'Approve karke publish karna hai?',
    approveBody: 'Badlav turant har learner ke liye live ho jaayenge.',
    comment: 'Comment (optional)',
    approved: 'Approve aur publish ho gaya',
    requestChanges: 'Badlav maango',
    requestTitle: 'Writer se badlav maango',
    requestBody: 'Batao kya alag hona chahiye. Writer ko yeh note dikhega.',
    requestComment: 'Kya badalna hai',
    sentBack: 'Writer ko wapas bhej diya',
    notReady: 'Yeh submission faisle ke intezaar me nahi hai.',
    publishedAs: (n) => `Curriculum version ${n} ke roop me publish hua.`,
    kind: { concept: 'Concept', lesson: 'Lesson', item: 'Sawaal', misconception: 'Galti' },
    action: {
      created: 'Banaya',
      edited: 'Badla',
      submitted: 'Review ke liye bheja',
      withdrawn: 'Wapas liya',
      approved: 'Approve hua',
      changes_requested: 'Badlav maange',
      published: 'Publish hua',
      publish_failed: 'Publish nahi ho paya',
    },
  },
  content: {
    title: 'Content versions',
    intro: 'Har publish ek version banata hai. Kuch bigde to pichhle version par wapas jao.',
    live: 'Abhi live',
    columns: { version: 'Version', note: 'Kya badla', published: 'Publish hua', status: 'Status' },
    caption: 'Content versions',
    current: 'Live',
    rollback: 'Is par wapas jao',
    rollbackTitle: (n) => `Version ${n} par wapas jaana hai?`,
    rollbackBody: 'Learners ko yeh version turant milta hai. Naye versions list me rehte hain.',
    note: 'Kyun (optional)',
    done: 'Wapas ho gaya',
    stats: (concepts, items) => `${concepts} concepts · ${items} sawaal`,
  },
  users: {
    title: 'Users',
    intro: 'Logon ko dhundo, writers ko unka role do, aur accounts suspend karo.',
    search: 'Naam ya email se dhundo',
    role: 'Role',
    status: 'Status',
    caption: 'Users',
    columns: { name: 'Naam', email: 'Email', role: 'Role', status: 'Status', joined: 'Join kiya' },
    roles: { student: 'Student', writer: 'Content writer', admin: 'Admin' },
    statuses: { active: 'Active', pending_consent: 'Parent ka intezaar', suspended: 'Suspended' },
    empty: 'Koi match nahi.',
    create: 'User jodo',
    createTitle: 'User jodo',
    name: 'Naam',
    email: 'Email',
    password: 'Temporary password',
    passwordHelp: 'Kam se kam 8 akshar. Woh Forgot password se badal sakte hain.',
    created: 'User ban gaya',
  },
  user: {
    back: 'Sabhi users',
    account: 'Account',
    verified: 'Email verify hui',
    unverified: 'Email verify nahi hui',
    joined: (date) => `${date} ko join kiya`,
    role: 'Role',
    saveRole: 'Role badlo',
    suspend: 'Suspend karo',
    reactivate: 'Dobara active karo',
    suspendTitle: 'Yeh account suspend karna hai?',
    suspendBody:
      'Woh har jagah se sign out ho jaate hain aur dobara active karne tak sign in nahi kar sakte.',
    updated: 'Account update ho gaya',
    self: 'Yeh aapka apna account hai. Isse koi aur hi badal sakta hai.',
    pending: 'Parent ke approve karne ka intezaar. Parent ke jawab dene par status badlega.',
    consent: 'Parent ki manzoori',
    consentRow: (email, status) => `${email} se poocha: ${status}`,
    trail: 'Is account me haal ke badlav',
    trailEmpty: 'Abhi kuch record nahi hua.',
  },
  classes: {
    title: 'Classes',
    intro: 'Har class, use kaun chalata hai, aur uska join code.',
    caption: 'Classes',
    columns: {
      name: 'Class',
      code: 'Join code',
      teacher: 'Teacher',
      members: 'Learners',
      created: 'Banayi',
    },
    create: 'Nayi class',
    createTitle: 'Class banao',
    name: 'Class ka naam',
    teacher: 'Kaun chalata hai',
    created: 'Class ban gayi',
    newCode: 'Naya code',
    newCodeDone: 'Purana code ab kaam nahi karta',
    delete: 'Delete karo',
    deleteTitle: 'Yeh class delete karni hai?',
    deleteBody: 'Learners class chhod dete hain. Unki apni progress ko kuch nahi hota.',
    deleted: 'Class delete ho gayi',
    roster: 'Roster',
    empty: 'Abhi koi class nahi.',
  },
  flags: {
    title: 'Feature flags',
    intro: 'Naye release ke bina kuch logon ya sabke liye cheezein on karo.',
    caption: 'Flags',
    columns: { key: 'Flag', on: 'On', rollout: 'Rollout', who: 'Kiske liye', updated: 'Badla' },
    everyone: 'Sabke liye',
    create: 'Naya flag',
    createTitle: 'Naya flag',
    editTitle: (key) => `${key} badlo`,
    key: 'Key',
    keyHelp: 'Chhote akshar, dots ya dash se jude, jaise map.3d',
    description: 'Yeh kya karta hai',
    enabled: 'Enabled',
    rollout: 'Kitne % logon ko milega',
    roles: 'Sirf in roles ke liye (koi nahi matlab sabke liye)',
    platforms: 'Sirf in platforms par (koi nahi matlab sab par)',
    minVersion: 'Sabse purana app version (optional)',
    value: 'On hone par milne wali value (JSON, optional)',
    valueBad: 'Yeh sahi JSON nahi hai.',
    saved: 'Flag save ho gaya',
    delete: 'Delete karo',
    deleteTitle: 'Yeh flag delete karna hai?',
    deleteBody: 'Jo apps ise maangte hain woh ise off maanenge.',
    deleted: 'Flag delete ho gaya',
    roleNames: { student: 'Student', writer: 'Writer', admin: 'Admin' },
    platformNames: { web: 'Web', android: 'Android' },
    empty: 'Abhi koi flag nahi.',
  },
  keys: {
    title: 'API keys',
    intro:
      'Developers ne public API ke liye jo keys banayi. Plan badlo, ya galat use hone wali key revoke karo.',
    caption: 'API keys',
    columns: {
      name: 'Naam',
      key: 'Key',
      owner: 'Maalik',
      plan: 'Plan',
      quota: 'Roz ki seema',
      today: 'Aaj',
      status: 'Status',
    },
    plans: { free: 'Free', partner: 'Partner' },
    active: 'Active',
    revoked: 'Revoked',
    edit: 'Plan badlo',
    editTitle: (name) => `${name} ka plan badlo`,
    plan: 'Plan',
    quota: 'Roz ki requests',
    saved: 'Key update ho gayi',
    revoke: 'Revoke karo',
    revokeTitle: 'Yeh key revoke karni hai?',
    revokeBody: 'Jo apps ise use karte hain woh turant band ho jaate hain.',
    revokedDone: 'Key revoke ho gayi',
    empty: 'Abhi kisi ne key nahi banayi.',
  },
  audit: {
    title: 'Audit log',
    intro: 'Kisne kya badla, aur kab. Entries badli nahi ja sakti.',
    caption: 'Audit log',
    columns: { when: 'Kab', who: 'Kisne', action: 'Kya', target: 'Kispar', details: 'Details' },
    action: 'Action',
    target: 'Target type',
    anyAction: 'Koi bhi action',
    anyTarget: 'Kuch bhi',
    system: 'System',
    empty: 'Koi entry match nahi karti.',
    show: 'Dikhao',
  },
  media: { title: 'Tasveerein' },
};

export const adminStrings = { en, 'hi-Latn': hi };
